# Generated by Django 2.1.2 on 2018-12-10 19:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('surname', models.CharField(max_length=90)),
                ('company_name', models.CharField(blank=True, max_length=500)),
                ('zip_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=350)),
                ('street', models.CharField(max_length=350)),
                ('house_number', models.CharField(max_length=7)),
                ('apartment_number', models.IntegerField(null=True, verbose_name=django.core.validators.MaxLengthValidator(7))),
                ('telephone_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(9)])),
                ('email_address', models.EmailField(max_length=250)),
                ('nip', models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EnvelopePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_to_1', models.FloatField(max_length=5)),
                ('courier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Courier')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('price', models.FloatField(max_length=5)),
                ('date', models.DateField()),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Courier')),
            ],
        ),
        migrations.CreateModel(
            name='PackPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_to_1', models.FloatField(max_length=5)),
                ('up_to_2', models.FloatField(max_length=5)),
                ('up_to_5', models.FloatField(max_length=5)),
                ('up_to_10', models.FloatField(max_length=5)),
                ('up_to_15', models.FloatField(max_length=5)),
                ('up_to_20', models.FloatField(max_length=5)),
                ('up_to_30', models.FloatField(max_length=5)),
                ('courier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Courier')),
            ],
        ),
        migrations.CreateModel(
            name='PalletPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_to_300', models.FloatField(max_length=5)),
                ('up_to_500', models.FloatField(max_length=5)),
                ('up_to_800', models.FloatField(max_length=5)),
                ('up_to_1000', models.FloatField(max_length=5)),
                ('courier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Courier')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('weight', models.FloatField()),
                ('type', models.CharField(max_length=10)),
                ('content', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_points', models.IntegerField(default=0)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Address')),
            ],
        ),
        migrations.CreateModel(
            name='SenderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Address')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='parcel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Parcel'),
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.RecipientAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.SenderAddress'),
        ),
    ]
