# Generated by Django 2.1.2 on 2018-12-10 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(7)]),
        ),
    ]
