# Generated by Django 2.1.2 on 2018-12-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20181210_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium_points',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
