# Generated by Django 2.1.2 on 2018-12-10 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20181210_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
