# Generated by Django 2.1.4 on 2019-01-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20190105_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='courier',
        ),
        migrations.AddField(
            model_name='opinion',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
    ]
