# Generated by Django 2.1.2 on 2019-01-05 23:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20190105_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('premium_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('gift_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GiftAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, validators=[django.core.validators.RegexValidator("^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]+$", 'To pole moze skladac sie tylko z liter.')])),
                ('surname', models.CharField(max_length=90, validators=[django.core.validators.RegexValidator("^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]+$", 'To pole moze skladac sie tylko z liter.')])),
                ('company_name', models.CharField(blank=True, max_length=500)),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('\\d{2}-\\d{3}', 'Podaj poprawny adres pocztowy NN-NNN')])),
                ('city', models.CharField(max_length=350, validators=[django.core.validators.RegexValidator("^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]+$", 'To pole moze skladac sie tylko z liter.')])),
                ('street', models.CharField(max_length=350)),
                ('house_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('apartment_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('telephone_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(9)])),
                ('email_address', models.EmailField(max_length=250)),
                ('nip', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='OrderGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Gift')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Profile')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.GiftAddress')),
            ],
        ),
    ]
